### PR TITLE
allow Github Actions failures with Julia nightly

### LINKED ISSUE #281: Allow Github Actions failures with Julia nightly
Cf https://github.com/JuliaSmoothOptimizers/SolverTest.jl/pull/6

### PR DESCRIPTION
**Pull request by dpo**
closes #281

### CODE REVIEW

**Comment by abelsiqueira** [comment]
It's less than ideal, because it still warns as failure here in the PR. However, I received no e-mail from failure, and the CI badge passes.

**Comment by dpo** [comment]
Actually, the badge says “failing” :-(.

**Comment by abelsiqueira** [comment]
The badge on SolverTest.jl README?

**Comment by amontoison** [comment]
Let's remove the nightly builds, what do you think ?
We still have one nighty build with CirrusCI on FreeBSD.

**Comment by dpo** [comment]
The badge here on the Krylov README.

**Comment by dpo** [comment]
Ah but the branch badge isn’t up to date. Sorry.

**Comment by abelsiqueira** [comment]
> The badge here on the Krylov README.

This badge is based on the master. It will only update after merging and the CI runs on it.

**Pull request merged**
