### PR TITLE
Add an attribute iterations for all variants of KrylovStats

### PR DESCRIPTION
**Pull request by amontoison**
- The number of iterations used by a Krylov solver is now returned.

### CODE REVIEW

**Comment by dpo** [comment]
What additional information does this provide that we didn't already have?

**Comment by amontoison** [comment]
We don't already have the number of iterations. We can only compute it with `iterations = length(stats.residuals) - 1`.

**Comment by dpo** [comment]
It can also be deduced from the number of operator-vector products. But more importantly, the number of iterations doesn't convey any relevant information in my opinion. It doesn't measure the amount of work performed. That's why we use the number of operator-vector products instead.

**Comment by amontoison** [comment]
PR not relevant

**Pull request closed without merging**
