### PR TITLE
Update kref! for GPU support

### LINKED ISSUE #215: minres_qlp performs scalar operations on GPU
Something is happening inside `minres_qlp` that seems to not be GPU-friendly

```julia
using Random, LinearAlgebra, CUDA, Krylov

Random.seed!(0)
n = 64
A = Matrix(Symmetric(rand(n, n)))
cA = CuArray(A)

b = ones(n)
cb = CuArray(b)

x, stats = minres_qlp(A, b);
cx, cstats = minres_qlp(cA, cb);
```
The last call leads to this warning:
```
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`
└ @ GPUArrays ~/.julia/packages/GPUArrays/eVYIC/src/host/indexing.jl:43
```

Subsequent timings look like
```julia
julia> @time x, stats = minres_qlp(A, b);
  0.000091 seconds (28 allocations: 8.391 KiB)

julia> CUDA.@time cx, stats = minres_qlp(cA, cb);
  0.088764 seconds (91.31 k CPU allocations: 3.673 MiB) (6 GPU allocations: 3.000 KiB, 0.06% gc time of which 79.26% spent allocating)
```

___

```
julia> versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by amontoison**
close #215 
Related PRs : https://github.com/JuliaGPU/CUDA.jl/pull/419, https://github.com/JuliaGPU/CUDA.jl/pull/427 and https://github.com/JuliaLang/julia/pull/35124

### CODE REVIEW

**Comment by amontoison** [comment]
@mtanneau can you check that this PR solves the problem with MINRES-QLP? You need the `gpu_kref!` branch of `amontoison/krylov.jl` and the master branch of `CUDA.jl`. I interfaced some functions associated to `CUBLAS` and Tim Besard merged the PR this morning.

**Comment by mtanneau** [comment]
> 
> 
> @mtanneau can you check that this PR solves the problem with MINRES-QLP? You need the `gpu_kref!` branch of `amontoison/krylov.jl` and the master branch of `CUDA.jl`. I interfaced some functions associated to `CUBLAS` and Tim Besard merged the PR this morning.

I will check that today, yes.

**Comment by dpo** [comment]
@amontoison give me the green light when this is ready to go.

**Comment by amontoison** [comment]
@mtanneau I checked with a Tesla P100 available at the GERAD and it works well too.
@dpo you can merge this PR.
Do you want to merge another PR like #206 and / or #128 before I create the release 0.5.3 ?

**Comment by amontoison** [comment]
```julia
using Random, LinearAlgebra, CUDA, Krylov

Random.seed!(0)
n = 2^12
A = Matrix(Symmetric(rand(n, n)))
cA = CuArray(A)

b = ones(n)
cb = CuArray(b)

minres_qlp(A, b)  # warm up
CUDA.@time minres_qlp(A, b);
```
-> 104.331374 seconds

```julia
CUDA.allowscalar(false)
minres_qlp(cA, cb) #warm up
CUDA.@time  minres_qlp(cA, cb);
```
-> 3.651324 seconds :muscle:

**Comment by mtanneau** [comment]
As a side remark, the CUDA version seems to be allocated some memory on the CPU.

```julia
julia> CUDA.@time minres_qlp(A, b);
 68.133280 seconds (56 CPU allocations: 578.141 KiB)

julia> CUDA.@time  minres_qlp(cA, cb);
  5.153048 seconds (2.99 M CPU allocations: 117.499 MiB, 0.21% gc time) (6 GPU allocations: 192.000 KiB, 0.00% gc time)
```
(these are all post warm-up runs)

No idea if it's expected nor where it comes from.

**Comment by amontoison** [comment]
Without the modifications of this PR:
```julia
CUDA.@time minres_qlp(cA, cb);
```
-> 860.511457 seconds :snail: 

For the allocations on CPU, I don't know where the problem comes from. It's difficult to profile it by ssh.

**Comment by dpo** [comment]
Thanks. Let's release.

**Pull request merged**
