### PR TITLE
Add more callbacks

### PR DESCRIPTION
**Pull request by geoffroyleconte**
- symmlq
- minres_qlp
- gmres
- dqgmres
- cg
- cg_lanczos
- cr
- bicgstab
- fom
- diom
- qmr

### CODE REVIEW

**Review by dpo — APPROVED** [review]
Looks great! Thank you!

@tmigot Is this the same kind of callback that you used in `cg_lanczos` with shifts?

**Comment by tmigot** [comment]
> Looks great! Thank you!
> 
> @tmigot Is this the same kind of callback that you used in `cg_lanczos` with shifts?

It is! I just need a fourth argument for the shifts: `callback(solver, A, b, shifts)`.

**Comment by dpo** [comment]
Would it make sense to store the shifts inside the solver object?

**Comment by tmigot** [comment]
> Would it make sense to store the shifts inside the solver object?

I am not sure as it is part of the problem as much is `A` and `b`, what do you think?

**Comment by dpo** [comment]
Do they change, or do only A and b change? Even if they change, we could have a method to update them inside the solver object.

**Comment by tmigot** [comment]
> Do they change, or do only A and b change? Even if they change, we could have a method to update them inside the solver object.

In theory, we could decide to resolve the system with more shifts if we were having an adaptive way of selecting them.

**Comment by geoffroyleconte** [comment]
@tmigot @dpo yes I will add different callback arguments for block methods and `cg_lanczos_shift` so I think `callback(solver, A, b, shifts)` makes sense.
I particular, can you check `bicgstab` in this PR? I left `callback(solver, A, b)` even though there is `c` because it is a keyword argument, but I can change it to `callback(solver, A, b, c)` if that is an issue.

**Comment by dpo** [comment]
In fact, why do you need to send A and b back to the user? The user passed them to the Krylov method, so (s)he has them...

**Comment by geoffroyleconte** [comment]
Yes, (s)he could directly add them to the default argument of the callback or to the structure if the callback is a `struct`. I thought that maybe it would be more user-friendly and easier to implement if only `A`, `b` and `solver` are needed for the callback (the arguments of the callback are the same as the arguments of the Krylov method), but I can remove `A` and `b` if you want.

**Comment by dpo** [comment]
Yes I would think that `callback(solver)` is enough.

**Comment by geoffroyleconte** [comment]
@dpo I've made the changes, can you review it once more please?
Also should I do it for all Krylov methods in this PR or can I separate it in several PRs?

**Review by dpo — APPROVED** [review]
Looks great! Thank you!

**Review by amontoison — APPROVED** [review]

**Comment by amontoison** [comment]
Thanks @geoffroyleconte !

**Pull request merged**
