### PR TITLE
Enable ARM64 build on DroneCI

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
> No such image: julia:1.4

:-(

**Comment by dpo** [comment]
arm/v7 only has Julia 1.0. arm64 has the latest.

**Comment by dpo** [comment]
Oh well, I've already reached the limit on DroneCI :-(.

Anyways, there's a test failure:
```
Simple stats
151	  solved: true
152	  inconsistent: false
153	  residuals:  [ 2.1e+02  2.1e+02  7.8e+01 ...  1.5e-01  1.5e-01  1.6e-02 ]
154	  Aresiduals: []
155	  status: solution xᶜ good enough given atol and rtol
156	USYMLQ: Relative residual:  1.4e-08
157	USYMLQ: Relative residual:  6.6e-09
158	USYMLQ: Relative residual:  1.9e-16
159	USYMLQ: Relative residual:  2.2e-16
160	USYMLQ: Relative residual:  0.0e+00
161	USYMLQ: Relative residual:  0.0e+00
162	USYMLQ: Relative residual:  9.2e-02
163	Test Failed at /drone/src/test/test_usymlq.jl:117
164	  Expression: resid ≤ usymlq_tol
165	   Evaluated: 0.09165908385903618 ≤ 1.0e-6
```

**Comment by amontoison** [comment]
Can I close this PR ?

**Comment by dpo** [comment]
No harm leaving it open. I haven't figured out what's wrong. I'll try with updated versions of Julia and the docker image when I get a chance.

**Comment by dpo** [comment]
This needs to be debugged in a Docker container...

**Comment by amontoison** [comment]
> This needs to be debugged in a Docker container...

Yes :(
I rebased the PR to see if the `mul!` revamp changed something.

**Comment by amontoison** [comment]
`ARM` architectures have [Tier 2 / Tier 3 support](https://julialang.org/downloads/).
The issue is probably not related to Krylov.jl.

**Comment by amontoison** [comment]
We should not merge this PR because we have limited credit with DroneCI but we can just rebase it at each major release to verify that tests with ARM64 processors passed (such as Apple M1).

**Comment by amontoison** [comment]
I added CI for ARM Macs with CirrusCI. We can close this PR.

**Pull request closed without merging**
