### PR TITLE
Accept integer types

### PR DESCRIPTION
**Pull request by abelsiqueira**
`r = 1.0*b` is the conversion to `Float64`, if the type is integer.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Travis nightly is failing because of DistributedArrays. Looks like they [solved](https://github.com/JuliaParallel/DistributedArrays.jl/pull/118) it, but haven't made a new release.

**Comment by dpo** [comment]
Ouch, `1.0* b` is so Matlab ;-).

I've been wanting to move the DistributedArray stuff to the examples, and out of the main package. Do you want to do that in another PR and rebase this one? (I'm also happy to do it.)

**Comment by abelsiqueira** [comment]
You mean the function `cg_lanczos_shift_par`?

**Comment by dpo** [comment]
Yes. What do you think? I don't think anybody used it and DistributedArrays causes constant grief.

**Comment by abelsiqueira** [comment]
Agreed

**Comment by abelsiqueira** [comment]
Regarding the `1.0*b`, I can change it to
```
convert(Array{promote_type(eltype(b), Float64), 1}, b)
```
I could test for `eltype(b) <: Integer` before doing this.

**Comment by dpo** [comment]
In time I would also like to support complex systems, so all that will probably change in the near future anyways.

**Comment by abelsiqueira** [comment]
Left as `1.0*b` for now, then.

**Comment by dpo** [comment]
ps: Appveyor is back!

**Comment by dpo** [comment]
Travis is stuck. What's new. Thanks for all this!

**Pull request merged**
