### PR TITLE
Update benchmark setup

### PR DESCRIPTION
**Pull request by MonssafToukal**

### CODE REVIEW

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by dpo** [comment]
`complex` is the name of a branch. Not sure if that helps locate the issue.

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by amontoison** [comment]
Awesome !!! Thank you Monssaf !

**Comment by dpo** [comment]
Congrats!

**Pull request merged**
