### PR TITLE
Poisson equation in polar coordinate

### PR DESCRIPTION
**Pull request by amontoison**
Example used  in the BiLQ article.

### CODE REVIEW

**Comment by dpo** [comment]
Great! Thanks! DIOM and DQGMRES would also be good candidates.

**Comment by amontoison** [comment]
You're right, I also added `DIOM` and `DQGMRES`.

I also tested CGS and the method is unable to solve it.
-> CGS: Relative residual:  6.8e+27
The condition number of A is squared with this method and with this problem the 
condition number of A is already `5 * 10^5`...

An other proof that `BiLQ` is relevant :+1:

**Comment by dpo** [comment]
Of course if the BiCG iterate sometimes fails to exist, what could possibly be said about CGS?!?!? 💣 💥 💣 

That raises the question of whether a transpose-free BiLQ would be useful.

**Comment by amontoison** [comment]
I should have a look first to see if it's possible. :thinking: 
It's weird that no transpose-free variants were developed for QMR and a multitude for BiCG (CGS, BiCGSTAB, TFQMR, ...).

**Comment by dpo** [comment]
You'll want to read https://link.springer.com/article/10.1023/A:1011637511962.

**Comment by dpo** [comment]
You know what to do :-)

**Comment by amontoison** [comment]
Tests failed because of DIOM. I forgot that I used a LU factorization with row pivoting by default in DIOM, I was able to make it working but I did a mistake in the residual norm estimate that I never solved.
By default we should use a LU factorization without row pivoting such that DIOM is equivalent to CG with reorthogonalization.

**Comment by dpo** [comment]
Hmmm why did the 32 bit Windows build fail and why did only one Cirrus build run?

**Comment by dpo** [comment]
Actually, there's a failure on Linux too: https://travis-ci.org/JuliaSmoothOptimizers/Krylov.jl/jobs/626565071#L320

**Comment by amontoison** [comment]
I increased the memory to see if it works on windows 32 bits.

**Comment by dpo** [comment]
Why is only one FreeBSD running???

**Comment by amontoison** [comment]
It was only a bug.

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
