### PR TITLE
Update the references -- DOI

### LINKED ISSUE #448: [documentation] Add a DOI for all references

### PR DESCRIPTION
**Pull request by amontoison**
close #448 
-> Five references don't have a DOI (3 thesis / 1 ETNA paper and a technical report)

* J. E. Craig, *Iterations Procedures for Simultaneous Equations*, Ph.D. Thesis, Department of Electrical Engineering, MIT, 1954.
* G. L.G. Sleijpen and D. R. Fokkema, *BiCGstab(ℓ) for linear equations involving unsymmetric matrices with complex spectrum*, Electronic Transactions on Numerical Analysis, 1, pp. 11--32, 1993.
* S.-C. T. Choi, *Iterative methods for singular linear equations and least-squares problems*, Ph.D. thesis, ICME, Stanford University, 2006.
* D. C.-L. Fong, *Minimum-Residual Methods for Sparse, Least-Squares using Golubg-Kahan Bidiagonalization*, Ph.D. Thesis, Stanford University, 2011.
* D. Orban, *The Projected Golub-Kahan Process for Constrained Linear Least-Squares Problems*. Cahier du GERAD G-2014-15, 2014.

@dpo Could you generate a DOI for your [technical report](https://www.researchgate.net/publication/264544703_The_Projected_Golub-Kahan_Process_for_Constrained_Linear_Least-Squares_Problems) ?

### CODE REVIEW

**Comment by dpo** [comment]
actually I have a few things to fix in that report related to SYMMLQ and how it decomposes into LSLQ and LNLQ (which were not knows at the time I wrote it). I'll try to do that soon.

**Comment by amontoison** [comment]
> actually I have a few things to fix in that report related to SYMMLQ and how it decomposes into LSLQ and LNLQ (which were not knows at the time I wrote it). I'll try to do that soon.

I'm not sure to understand your answer.
You don't want to generate a DOI on ResearchGate because you only want to give a link to the future version of this technical report ?

**Comment by dpo** [comment]
Sorry I forgot that that report was already on RG. Here's the DOI: http://dx.doi.org/10.13140/RG.2.2.17443.99360

**Comment by amontoison** [comment]
Thanks !

**Pull request merged**
