### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amontoison**
@dpo Can you synchronize Krylov.jl with Zenedo ?
The last release is `0.5.1`.
I can only update packages of `bbopt` organization.

### CODE REVIEW

**Comment by dpo** [comment]
Zenodo is down :-(

**Comment by amontoison** [comment]
> Zenodo is down :-(

Zenodo is working now :)

**Comment by dpo** [comment]
No. Still down.

Releases have been broken since you made this change: https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/205/files

The error is that the publication date is in the wrong format.

**Comment by amontoison** [comment]
> No. Still down.
> 
> Releases have been broken since you made this change: https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/205/files
> 
> The error is that the publication date is in the wrong format.

Well spotted !
I opened a PR to fix it (#348).

**Pull request merged**
