### PR TITLE
Update CI, TagBot and documentation workflows

### PR DESCRIPTION
**Pull request by JSOBot**

### CODE REVIEW

**Comment by amontoison** [comment]
The docstrings for Krylov methods and the other functions are not in the same section.
This pull request is not relevant for this repository.

**Comment by dpo** [comment]
The idea is to make the docs automatic and uniform. I would rather not go and modify the docs by hand each time. The references are supposed to be just that: a reference.

**Comment by dpo** [comment]
We could set `strict=false` in `make.jl` so Documenter doesn’t complain that docstrings are included multiple times. Would that be better?

**Comment by amontoison** [comment]
Yes, I like this idea. Let's get back `api.md` and set `strict=false` in the `make.jl` file.

**Pull request merged**
