### PR TITLE
Multiprecision support

### PR DESCRIPTION
**Pull request by amontoison**
The majority of the modifications are `1.0` that become `one(T)`, `0.0` that become `zero(T)` and small type stable stuff.

#103 
#126

### CODE REVIEW

**Comment by amontoison** [comment]
@abelsiqueira Do you have any idea with `Travis` is not working anymore when I open a pull request?
I did a fresh clone of Krylov.jl and synchronised again my master branch.

**Comment by abelsiqueira** [comment]
Not sure. Is it rebased? Could you try `git --amend -a` the last commit and force push?

**Comment by amontoison** [comment]
I did it and I don't have automatic integration at all now. Any clue?

**Comment by dpo** [comment]
Are `.travis.yml` and `appveyor.yml` in your branch?

**Comment by abelsiqueira** [comment]
Someone just complained about a similar issue on Gitter: https://gitter.im/JuliaOpt/JuMP-dev

**Comment by dpo** [comment]
The commit `Multiprecision support for CG_LANCZOS_SHIFT_SEQ` just ran on Appveyor, but nothing ran on TravisCI. However, I don't see that commit in this pull request...?!?!

**Comment by amontoison** [comment]
Yes, `.travis.yml` and `appveyor.yml` are in my branch. I think it's a bug.
And `Multiprecision support for CG_LANCZOS_SHIFT_SEQ` is in this pull request, it's my last commit.
I don't know why you don't see it?!

**Comment by dpo** [comment]
Ah, I just missed it.

**Comment by dpo** [comment]
Could you rebase / reopen this if your travis config is fixed?

**Comment by dpo** [comment]
YES!

**Comment by dpo** [comment]
🤘

**Pull request merged**
