### PR TITLE
`show` function for KrylovSolvers

### PR DESCRIPTION
**Pull request by tmigot**
The suggested `show` would print:
```
julia> cg_solver
CgSolver{Float64, Vector{Float64}}:
Δx: Vector{Float64} of length 0
x: Vector{Float64} of length 10
r: Vector{Float64} of length 10
p: Vector{Float64} of length 10
Ap: Vector{Float64} of length 10
z: Vector{Float64} of length 0
Simple stats
 solved: false
 inconsistent: false
 residuals: []
 Aresiduals: []
 status: unknown
```
@amontoison if it looks good for you I will add the unit tests for the coverage.

### CODE REVIEW

**Comment by amontoison** [comment]
@tmigot We could display all informations in a table, what do you think ?

show

**Comment by tmigot** [comment]
```
┌────────────────────┬──────────────────────────┬──────────────────┐
│CgLanczosShiftSolver│        Precision: Float64│ Architecture: CPU│
├────────────────────┼──────────────────────────┼──────────────────┤
│           Attribute│                      Type│              Size│
├────────────────────┼──────────────────────────┼──────────────────┤
│                  Mv│           Vector{Float64}│                10│
│             Mv_prev│           Vector{Float64}│                10│
│             Mv_next│           Vector{Float64}│                10│
│                   v│           Vector{Float64}│                 0│
│                   x│   Vector{Vector{Float64}}│            2 x 10│
│                   p│   Vector{Vector{Float64}}│            2 x 10│
│                   σ│           Vector{Float64}│                 2│
│                δhat│           Vector{Float64}│                 2│
│                   ω│           Vector{Float64}│                 2│
│                   γ│           Vector{Float64}│                 2│
│              rNorms│           Vector{Float64}│                 2│
│           converged│                 BitVector│                 2│
│              not_cv│                 BitVector│                 2│
└────────────────────┴──────────────────────────┴──────────────────┘
LanczosShift stats
 solved: false
 residuals: [Float64[], Float64[]]
 indefinite: Bool[0, 0]
 ‖A‖F: NaN
 κ₂(A): NaN
 status: unknown
```

**Comment by amontoison** [comment]
Perfect ! :ok_hand: 
We just have a problem with `w̅` and `d̅`, they are not correctly displayed in terminal.
We could change the variable name for `wbar` and `dbar` (in the solvers only), what do you think ?
It concerns `SYMMLQ`, `LNLQ`, `LSLQ`, `TriLQR`, `BiLQ`, `BiLQR` and `USYMLQ`.
display

**Comment by dpo** [comment]
Is it a font issue or an issue with PrettyTables?

**Comment by amontoison** [comment]
A font issue, the table is created with `@printf` function. We don't use `PrettyTables` although it looks like it.

**Review by amontoison — APPROVED** [review]

**Comment by amontoison** [comment]
Thanks Tangi !!!

**Pull request merged**
