### PR TITLE
Remove files for formatting

### PR DESCRIPTION
**Pull request by amontoison**
A PR to format Krylov.jl was never opened.

### CODE REVIEW

**Comment by dpo** [comment]
Why remove them though?

**Comment by amontoison** [comment]
CI always failed after a PRs was merged due to this workflow.
I don't know how to deactivate the workflow without removing the files.

**Comment by dpo** [comment]
Could you point to an exmple?

**Comment by amontoison** [comment]
format-pr

**Comment by dpo** [comment]
I meant give a link so we can go and examine the log.

**Comment by amontoison** [comment]
Sorry, https://github.com/JuliaSmoothOptimizers/Krylov.jl/runs/2678184774

**Pull request merged**
