### PR TITLE
Bumping version to 0.8.3

### PR DESCRIPTION
**Pull request by AntoninKns**
Bumping krylov version to v0.8.3 in order to adapt to latest changes.

### CODE REVIEW

**Comment by dpo** [comment]
I wonder why 0.8.2 doesn't appear in the releases.

**Comment by AntoninKns** [comment]
I was wondering that too, because I can still download it.

**Comment by amontoison** [comment]
> I wonder why 0.8.2 doesn't appear in the releases.

Let's see if it was just a bug with GitHub or an issue a workflow.

**Comment by dpo** [comment]
Now you have 0.8.3 without 0.8.2.

**Comment by amontoison** [comment]
> Now you have 0.8.3 without 0.8.2.

It's fixed, I added a tag v0.8.2 and the associated release.

**Pull request merged**
