### PR TITLE
Update dependencies, use Julia 1.3 on docs and coverage and release 0.4

### PR DESCRIPTION
**Pull request by abelsiqueira**
First release supporting LinearOperators 1.0.
Preparing for Krylov 1.0.

### CODE REVIEW

**Comment by dpo** [comment]
Great, thanks. Give me a chance to review #159 before releasing. Probably later this week.

**Comment by amontoison** [comment]
For Krylov.jl 1.0, I think we could do the release  when `LNLQ` and `USYMLQR` will be added.

**Comment by dpo** [comment]
I think this needs to be rebased.

**Comment by abelsiqueira** [comment]
This is rebased now.

**Comment by dpo** [comment]
Thank you.

**Pull request merged**
