### PR TITLE
Add function signature within its docstring

### PR DESCRIPTION
**Pull request by amontoison**
#207

### CODE REVIEW

**Comment by dpo** [comment]
:-(
what about automatically-generated signatures in the docstring? The advantage is that they stay in sync with the actual function signature.

**Comment by amontoison** [comment]
We don't have any news from `JuliaDocs/DocStringExtensions.jl` for our problem. Should we add signatures in the docstring by hand for the moment? I will be better than nothing.

**Comment by dpo** [comment]
Sure. DocstringExtensions is a bit disappointing... :-(

**Comment by amontoison** [comment]
It's not fun to do, but It should help a lot of users.

**Comment by dpo** [comment]
Indeed! Thank you!

**Pull request merged**
