### PR TITLE
Update with JSOBestieTemplate for Krylov

### PR DESCRIPTION
**Pull request by tmigot**
Automated update using JSOBestieTemplate

### CODE REVIEW

**Comment by amontoison** [comment]
@tmigot Why do remove `CommentPR.yml`?
It allows to update the previous breakage message. Otherwise after 35 rebase, we have 35 messages and it's just spamming.

**Comment by amontoison** [comment]
> @tmigot Why do you remove `CommentPR.yml`? It allows to update the previous breakage message. Otherwise after 35 rebase, we have 35 messages and it's just spamming.

**Review by amontoison — APPROVED** [review]

**Comment by tmigot** [comment]
Hi @amontoison ! Sorry, I didn't reply in time, I was also looking for some time to update the script. I see that you were faster :).
Can you open a PR here https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl to include your changes ?

**Comment by amontoison** [comment]
It was planned :)
I just want to check if it works as intended before in this PR #927

**Comment by tmigot** [comment]
Also, note that with this script we only cover JSO packages in the Breakage.
So, if you would want to test other packages I would suggest to add another script Krylov.jl-specific.

**Pull request merged**
