### PR TITLE
Add new tests for GPUs

### PR DESCRIPTION
**Pull request by amontoison**
A new release of `GPUArrays.jl` is available.
My generic fallbacks for `dot` and `reflect!` should work now.
It will solve some issues with Intel / Apple M1 GPUs.

### CODE REVIEW

**Comment by amontoison** [comment]
The culprit is the stopping condition based on the backward error...
I should have known!
This condition is not reliable at all because it's an upper bound of the backward error.
It's nice for theoretical articles but in practice it doesn't fit well in the implementations.

**Comment by amontoison** [comment]
@jpsamaroo
Do you know how to solve the error with AMDGPU.jl (buildkite checks)?

**Comment by amontoison** [comment]
It seems that Julia 1.9 + master branch of AMDGPU.jl solved the problem with AMD GPUs.
I have the following message but the tests passed:
```
LoadLib(libhsa-amd-aqlprofile64.so) failed: libhsa-amd-aqlprofile64.so: cannot open shared object file: No such file or directory
```

**Comment by jpsamaroo** [comment]
@amontoison good to hear! AMDGPU CI has been shaky recently, the CI machines enter a state where some GPUs just stop working and we need to reboot. They usually show up as `ERROR_OUT_OF_RESOURCES`.

**Comment by amontoison** [comment]
I understand now what is the issue if I encounter a `ERROR_OUT_OF_RESOURCES` with buildkite CI. Thanks!
We will be able to test the RocSPARSE support here as soon as it will be available in AMDGPU.jl.

**Pull request merged**
