### PR TITLE
Fix issues with Julia 1.7

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by dpo** [comment]
Great. I was wondering about those failures. There’s still something related to LinearOperators though :-(

**Comment by amontoison** [comment]
Let's wait the official release 1.7 to see if we still have the same issues.

**Comment by amontoison** [comment]
> Great. I was wondering about those failures. There’s still something related to LinearOperators though :-(

The issue is related to the function `size` of `SparseMatrixCSC` that returns `Int32` now. I think that it's a bug because we still have `Int64` with Float32 dense matrices.

**Comment by amontoison** [comment]
I found the culprit : https://github.com/JuliaLang/julia/pull/39645

**Comment by amontoison** [comment]
`nrow` and `ncol` attributes of LinearOperators should be `Integer` instead of `Int`.
@geoffroyleconte Can you take this into account for the revamp ?

**Review by dpo — APPROVED** [review]

**Pull request merged**
