### PR TITLE
Remove random tests

### LINKED ISSUE #5: CRMR tests sometimes pass, sometimes fail
Compare
https://travis-ci.org/JuliaOptimizers/Krylov.jl/builds/128475745
and
https://travis-ci.org/jagot/Krylov.jl/builds/128475739

which both test the same commit.

### PR DESCRIPTION
**Pull request by amontoison**
I didn't remove random data used to build `InverseLBFGSOperator`.
I used a fixed seed instead.
fix #5
#81

### CODE REVIEW

**Comment by dpo** [comment]
This is great, many thanks! In order to avoid repetitions, I wonder if we could have all the test systems in a separate file and give them names. For example,
```julia
A, b = under_inconsistent()
A, b = under_consistent()
...
```
What do you think?

**Comment by amontoison** [comment]
It's a good idea. I will add them in `test_utils.jl`.

**Comment by dpo** [comment]
@amontoison It would be great if you found the time to separate out the tests at some point.

**Comment by amontoison** [comment]
Sorry for the delay.

**Comment by dpo** [comment]
Excellent, thank you!

**Pull request merged**
