### PR TITLE
Sanitise code

### PR DESCRIPTION
**Pull request by amontoison**
+ <= and >=
+ white space
+ semi colon

### CODE REVIEW

**Comment by dpo** [comment]
Thank you! That was long overdue...

**Comment by amontoison** [comment]
Some brave semicolons are still present. They didn't get catch by my `sed` commands :angry:

**Comment by dpo** [comment]
Brave? Do you mean pesky?

**Comment by amontoison** [comment]
I said brave because they had resisted to the `sed` commands. But pesky is also appropriate.

**Pull request merged**
