### PR TITLE
comment out failing tests

### PR DESCRIPTION
**Pull request by dpo**
#560 #244
@amontoison

Note that

> The Arm architecture provides high-performance and high-efficiency hardware support for floating-point operations in half-, single-, and double-precision arithmetic. Arm floating point technology is fully IEEE-754 compliant with full software library support.

(https://developer.arm.com/architectures/instruction-sets/floating-point)

I'll try to enable verbosity during those tests to find out what's going on.

### CODE REVIEW

**Comment by amontoison** [comment]
Note that Armv8-A and Armv8-R Architectures support:
> Configurable rounding modes
> Configurable Default NaN behavior
> Configurable Flush-to-zero behavior

Julia is maybe compiled with a different rounding mode for ARM / ARM64 architectures.

**Comment by dpo** [comment]
At the command line:
```julia
julia> A = get_div_grad(4, 4, 4)
julia> n = size(A, 1)
julia> m = div(n, 2)
julia> Ao  = A[:,1:m]
julia> b = Ao * ones(m)
julia> cr_solver = CrSolver(n, n, Vector{Float64})
julia> b = 5 * b  # first pass through the loop
julia> solve!(cr_solver, A, b, verbose = 1)
CR: system of 64 equations in 64 variables
    k      ‖x‖      ‖r‖     quad
    0   0.0e+00  6.3e+01  0.0e+00
    1   1.7e+01  2.6e+01 -6.3e+02
    2   2.3e+01  1.3e+01 -7.5e+02
    3   2.6e+01  6.4e+00 -7.9e+02
    4   2.7e+01  4.1e+00 -7.9e+02
    5   2.8e+01  1.6e+00 -8.0e+02
    6   2.8e+01  5.7e-01 -8.0e+02
    7   2.8e+01  1.3e-01 -8.0e+02
    8   2.8e+01  1.8e-07 -8.0e+02

Simple stats
 niter: 8
 solved: true
 inconsistent: false
 residuals: []
 Aresiduals: []
 κ₂(A): []
 status: solution good enough given atol and rtol

julia> issolved(cr_solver)
true
```
The output above matches what I observe if I add `verbose = 1` in the unit test. It also matches the same test on macOS Intel, except that the last iteration is
```julia
    8   2.8e+01  3.6e-07 -8.0e+02
```

For the next pass through the loop:
```julia
julia> A = 2 * A
julia> b = 5 * b
julia> solve!(cr_solver, A, b, verbose = 1)
CR: system of 64 equations in 64 variables
    k      ‖x‖      ‖r‖     quad
    0   0.0e+00  3.2e+02  0.0e+00
    1   4.3e+01  1.3e+02 -7.8e+03
    2   5.8e+01  6.3e+01 -9.4e+03
    3   6.5e+01  3.2e+01 -9.8e+03
    4   6.8e+01  2.0e+01 -9.9e+03
    5   7.0e+01  8.2e+00 -1.0e+04
    6   7.1e+01  2.8e+00 -1.0e+04
    7   7.1e+01  6.4e-01 -1.0e+04
    8   7.1e+01  5.7e-06 -1.0e+04
    9   7.1e+01  5.7e-06 -1.0e+04
    # ... nothing changes in the output until ...
    128   7.1e+01  5.7e-06 -1.0e+04

Simple stats
 niter: 128
 solved: false
 inconsistent: false
 residuals: []
 Aresiduals: []
 κ₂(A): []
 status: maximum number of iterations exceeded
```
On macOS Intel, the output is
```julia
julia> solve!(cr_solver, A, b, verbose = 1)
CR: system of 64 equations in 64 variables
    k      ‖x‖      ‖r‖     quad
    0   0.0e+00  3.2e+02  0.0e+00
    1   4.3e+01  1.3e+02 -7.8e+03
    2   5.8e+01  6.3e+01 -9.4e+03
    3   6.5e+01  3.2e+01 -9.8e+03
    4   6.8e+01  2.0e+01 -9.9e+03
    5   7.0e+01  8.2e+00 -1.0e+04
    6   7.1e+01  2.8e+00 -1.0e+04
    7   7.1e+01  6.4e-01 -1.0e+04
    8   7.1e+01  3.4e-06 -1.0e+04
```

**Comment by amontoison** [comment]
The test with CR just failed with a GitHub Actions build on Ubuntu :thinking:

**Comment by dpo** [comment]
@amontoison I added CI on macOS M1 with Julia 1.7.2 to this PR. This is for information only since Julia isn't yet reliable on that platform.

**Comment by amontoison** [comment]
Thanks @dpo! Can you uncomment the failing tests ?
It will be easier to fix them with CI on macOS M1.

**Comment by amontoison** [comment]
Thanks @dpo! Can you uncomment the failing tests ?
It will be easier to fix them with CI on macOS M1.

**Comment by amontoison** [comment]
The `CI_M1` script is unable to run the tests :worried:

**Comment by dpo** [comment]
It was down. It's up now.

**Comment by amontoison** [comment]
Thanks @dpo!

**Pull request merged**
